### ISSUE TITLE
Todo-list for Frontend CE

### ISSUE THREAD

**Issue by joao-gsneto** [CeJobs/cejobs-front#1]
# Frontend Todo
- [ ] Single job page
- [ ] Sidebar to list opened jobs
- [ ] Sidebar to list common job categories
- [ ] Sidebar to list recent companies  with jobs
- [ ] New Job page
- [ ] Quem Somos page
- [ ] Advanced search page
